const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s); let connected=true;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function show(view){$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==view));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={overview:'Vehicle overview',guided:'Guided session',live:'Live data',faults:'Diagnostic trouble codes',service:'Service actions',sessions:'Session history'};$('#pageTitle').textContent=titles[view]}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
function value(id,n,unit){const e=$('#'+id);if(e)e.innerHTML=`${Number(n).toFixed(id==='rpm'?0:2)} <em>${unit}</em>`}
function renderLive(v){value('rpm',v.rpm,'rpm');value('coolant',v.coolant,'°C');value('battery',v.battery,'V');value('throttle',v.throttle,'%');$('#liveGrid').innerHTML=[['rpm','Engine speed','rpm'],['coolant','Coolant temperature','°C'],['battery','System voltage','V'],['throttle','Throttle position','%'],['air','Intake air temperature','°C'],['lambda','Lambda correction','λ']].map(x=>`<article class="metric"><small>${x[1].toUpperCase()}</small><strong>${Number(v[x[0]]).toFixed(x[0]==='rpm'?0:2)} <em>${x[2]}</em></strong><div class="bar"><i style="width:${Math.min(92,Math.max(12,Number(v[x[0]])*3))}%"></i></div><label>Live simulator value</label></article>`).join('')}
function renderFaults(f){$('#faultCount').textContent=f.length;$('#faultSummary').textContent=f.length?`${f.length} code${f.length>1?'s':''} require attention`:'No active or stored codes';$('#faultList').innerHTML=f.length?f.map(x=>`<div class="fault"><div class="fault-code">${x.code}</div><div class="fault-info"><strong>${x.title}</strong><small>Engine management · ${x.severity==='warning'?'Check when convenient':'Historical record'}</small></div><div class="fault-status">${x.status.toUpperCase()}</div></div>`).join(''):`<div class="panel session-empty"><div class="empty-icon">✓</div><h3>No diagnostic trouble codes</h3><p>The simulated ECU reports a clean fault memory.</p></div>`}
async function refresh(){try{const r=await fetch('/api/status');const d=await r.json();renderLive(d.values);renderFaults(d.faults)}catch(e){toast('Local simulator is unavailable')}}
$('#connectBtn').onclick=async()=>{const endpoint=connected?'/api/disconnect':'/api/connect';await fetch(endpoint,{method:'POST'});connected=!connected;$('#connectBtn').textContent=connected?'Disconnect':'Connect';toast(connected?'Simulator connected':'Simulator disconnected')};$('#clearBtn').onclick=async()=>{await fetch('/api/clear-faults',{method:'POST'});toast('Fault memory cleared in simulator');refresh()};['#exportBtn','#exportBtn2'].forEach(s=>$(s)?.addEventListener('click',async()=>{await fetch('/api/export',{method:'POST'});toast('Report exported — simulator session ready')}));$$('[data-step]').forEach(b=>b.onclick=()=>{const labels={adapter:'Adapter check started — simulator is ready',identify:'ECU identification queued for the hardware transport',health:'Health check opened — review live values and faults'};toast(labels[b.dataset.step]||'Workflow step selected')});refresh();setInterval(refresh,1000);
